### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by draffensperger** [jasonlong/vim-textobj-css#2]
Could you please add a license to clarify how this can be used, e.g. the Vim license or the Apache 2.0 license?

**Comment by jasonlong** [comment]
Thanks for the ping @draffensperger. I just added The Unlicense to this project. This obviously just applies to my css plugin and not to [vim-textobj-user](https://github.com/kana/vim-textobj-user) itself – which, surprisingly, doesn't have a license either.

**Comment by draffensperger** [comment]
The license for vim-textobj-user itself is MIT, but it's not obvious from the repo. See this in the source: https://github.com/kana/vim-textobj-user/blob/e231b65797b5765b3ee862d71077e9bd56f3ca3e/autoload/textobj/user.vim#L4
